# dev/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-fullstack-deployment
  labels:
    app: flask-fullstack
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: flask-fullstack
  template:
    metadata:
      labels:
        app: flask-fullstack
    spec:
      containers:
      - name: flask-fullstack
        image: flask-fullstack-app:v3 # Image from local registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000  # Flask app listens on port 5000
