pipeline {
  agent any

  environment {
    IMAGE_NAME     = "flask-todo-app"        // Base name for Docker image, noregistry prefix
  }

  stages {

    stage('Clone Backend Code') {
      steps {
        echo "Cloning backend code"
        sh 'ls -l dev/bkend/app'             // Confirm app files exist
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          // Get Git short hash for tagging
          COMMIT_HASH = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          
          // Save as env var so next stage can use
          env.IMAGE_TAG = "${IMAGE_NAME}:${COMMIT_HASH}"

          // Build Docker image
          dir('dev/bkend/app') {
            sh "docker build -t ${env.IMAGE_TAG} ."
          }
        }
      }
    }

    stage('Load Image into Minikube') {
      steps {
        script {
          // Load the image into Minikube (so K8s can use it)
          sh "minikube image load ${env.IMAGE_TAG}"
        }
      }
    }

    stage('Done') {
      steps {
        echo "Image loaded into Minikube: ${env.IMAGE_TAG}"
        echo "To deploy it, run:"
        echo "kubectl set image deployment/flask-todo-deployment flask-todo=${env.IMAGE_TAG} --record"
      }
    }

  }
}
